# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Blog Vivere Plus
email: vivereplus@vivereplus.sk
description: >- # this means to ignore newlines until "baseurl:"
  VIVERE PLUS, s.r.o. je modernou spoločnosťou poskytujúcou lektorské a konzultačné služby v oblasti Soft Skills, pôsobiacou na slovenskom trhu od roku 2008. Jej hlavným cieľom je prostredníctvom komplexného súboru služieb pomáhať, viesť a inšpirovať klientov k životnému štýlu smerujúcemu k spokojnosti a úspechu vo všetkých oblastiach života. Realizácia školení, tréningových programov, workshopov a osobných konzultácií prebieha v Bratislave, alebo na mieste určenom zadávateľom, prípadne v kongresových priestoroch PoľnoSme v Palárikove (www.wellnesspalarikovo.sk).
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
locale: sk

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Mária Černáková"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "S dôverou a radosťou rozvíjam svoje schopnosti a talent, aby som tak umožnila využívať a rozširovať schopnosti, talent a potenciál druhých ľudí. Motivujem ich, aby mali možnosť rozhodnúť sa pre im fungujúce riešenia, ktoré ich privedú k úspechu. Som pozorovateľkou života, ktorý je pre mňa neustálou inšpiráciou."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://vivereplus.sk"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/maria.cernakova_vivereplus"

footer:
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://vivereplus.sk"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/maria.cernakova_vivereplus"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
